export const DEPTS = ["Graphic Design", "Interior Design", "Fine Arts", "Fashion Design"];
export const WEEKS = 9;

export const SEED_GROUPS = [
  {id:"g1",name:"Level 6 Graphic",department:"Graphic Design",year:3,term:1},
  {id:"g2",name:"Level 5 Modular May 26 (Graphic)",department:"Graphic Design",year:1,term:1},
  {id:"g3",name:"Level 6 Modular May 26 (Graphic)",department:"Graphic Design",year:1,term:1},
  {id:"g4",name:"Level 6 Modular Jan 26 (Graphic)",department:"Graphic Design",year:1,term:1},
  {id:"g5",name:"Level 5 Modular Jan 26 (Graphic)",department:"Graphic Design",year:1,term:1},
  {id:"g6",name:"KNEC May 2025 (Graphic)",department:"Graphic Design",year:2,term:1},
  {id:"g7",name:"NITA (Graphic)",department:"Graphic Design",year:1,term:1},
  {id:"g8",name:"Level 4 Modular May 26 (Interior) T1",department:"Interior Design",year:1,term:1},
  {id:"g9",name:"Level 5 Modular May 26 (Interior)",department:"Interior Design",year:1,term:1},
  {id:"g10",name:"Level 6 Modular May 26 (Interior)",department:"Interior Design",year:1,term:1},
  {id:"g11",name:"Level 4 Modular May 26 (Interior) T2",department:"Interior Design",year:1,term:2},
  {id:"g12",name:"Level 6 May 25 (Interior)",department:"Interior Design",year:1,term:1},
  {id:"g13",name:"Level 6 Interior",department:"Interior Design",year:3,term:1},
  {id:"g14",name:"Level 6 Fine Arts",department:"Fine Arts",year:3,term:1},
  {id:"g15",name:"Level 5 Modular May 26 (Fine Arts)",department:"Fine Arts",year:1,term:1},
  {id:"g16",name:"KNEC May 2025 (Fine Arts)",department:"Fine Arts",year:2,term:1},
  {id:"g17",name:"Level 5 Modular Jan 26 (Fine Arts)",department:"Fine Arts",year:1,term:1},
  {id:"g18",name:"Level 4 Mod 1 May 26 (Fashion)",department:"Fashion Design",year:1,term:1},
  {id:"g19",name:"Level 5 Mod 1 May 26 (Fashion)",department:"Fashion Design",year:1,term:1},
  {id:"g20",name:"Level 5 Mod 2 May 26 (Fashion)",department:"Fashion Design",year:1,term:1},
  {id:"g21",name:"Level 6 Mod 2 May 24 (Fashion)",department:"Fashion Design",year:3,term:1},
  {id:"g22",name:"KNEC Mod 2 May 2025 (Fashion)",department:"Fashion Design",year:2,term:2},
];

export const SEED_UNITS = [
  // Level 6 Graphic (g1)
  {id:"u1",name:"Environment",group_id:"g1",sessions_per_day:1},
  {id:"u2",name:"Packaging Design",group_id:"g1",sessions_per_day:1},
  {id:"u3",name:"Graphic Reproduction",group_id:"g1",sessions_per_day:1},
  {id:"u4",name:"Publication Design",group_id:"g1",sessions_per_day:1},
  {id:"u5",name:"UI Design",group_id:"g1",sessions_per_day:1},
  {id:"u6",name:"Photography",group_id:"g1",sessions_per_day:1},
  {id:"u7",name:"OSHA",group_id:"g1",sessions_per_day:1},
  {id:"u8",name:"Graphic Illustration",group_id:"g1",sessions_per_day:2},
  // Level 5 Modular May 26 Graphic (g2)
  {id:"u9",name:"Christian Ethics",group_id:"g2",sessions_per_day:1},
  {id:"u10",name:"Hand Drawing",group_id:"g2",sessions_per_day:2},
  {id:"u11",name:"Digital Literacy",group_id:"g2",sessions_per_day:2},
  {id:"u12",name:"Elements",group_id:"g2",sessions_per_day:1},
  {id:"u13",name:"Conceptualize",group_id:"g2",sessions_per_day:2},
  {id:"u14",name:"Digital Graphics",group_id:"g2",sessions_per_day:3},
  // Level 6 Modular May 26 Graphic (g3)
  {id:"u15",name:"Christian Ethics",group_id:"g3",sessions_per_day:1},
  {id:"u16",name:"Hand Drawing",group_id:"g3",sessions_per_day:2},
  {id:"u17",name:"Digital Literacy",group_id:"g3",sessions_per_day:2},
  {id:"u18",name:"Elements",group_id:"g3",sessions_per_day:1},
  {id:"u19",name:"Conceptualize",group_id:"g3",sessions_per_day:2},
  {id:"u20",name:"Digital Graphics",group_id:"g3",sessions_per_day:3},
  // Level 6 Modular Jan 26 Graphic (g4)
  {id:"u21",name:"Christian Ethics",group_id:"g4",sessions_per_day:1},
  {id:"u22",name:"Elements",group_id:"g4",sessions_per_day:2},
  {id:"u23",name:"Conceptualize",group_id:"g4",sessions_per_day:2},
  {id:"u24",name:"Hand Drawing",group_id:"g4",sessions_per_day:2},
  {id:"u25",name:"Digital Literacy",group_id:"g4",sessions_per_day:2},
  {id:"u26",name:"Digital Graphics",group_id:"g4",sessions_per_day:1},
  // Level 5 Modular Jan 26 Graphic (g5)
  {id:"u27",name:"Christian Ethics",group_id:"g5",sessions_per_day:1},
  {id:"u28",name:"Elements",group_id:"g5",sessions_per_day:2},
  {id:"u29",name:"Conceptualize",group_id:"g5",sessions_per_day:2},
  {id:"u30",name:"Hand Drawing",group_id:"g5",sessions_per_day:2},
  {id:"u31",name:"Digital Literacy",group_id:"g5",sessions_per_day:2},
  {id:"u32",name:"Digital Graphics",group_id:"g5",sessions_per_day:1},
  // KNEC May 2025 Graphic (g6)
  {id:"u33",name:"Entrepreneurship",group_id:"g6",sessions_per_day:1},
  {id:"u34",name:"S/MGT",group_id:"g6",sessions_per_day:1},
  {id:"u35",name:"Graphic Reproduction",group_id:"g6",sessions_per_day:1},
  {id:"u36",name:"Art & Design",group_id:"g6",sessions_per_day:1},
  {id:"u37",name:"Typography",group_id:"g6",sessions_per_day:1},
  {id:"u38",name:"Packaging",group_id:"g6",sessions_per_day:1},
  {id:"u39",name:"Advertising",group_id:"g6",sessions_per_day:1},
  {id:"u40",name:"CAD",group_id:"g6",sessions_per_day:1},
  {id:"u41",name:"Research Methods",group_id:"g6",sessions_per_day:1},
  {id:"u42",name:"Publications",group_id:"g6",sessions_per_day:1},
  {id:"u43",name:"IMM",group_id:"g6",sessions_per_day:1},
  {id:"u44",name:"CID",group_id:"g6",sessions_per_day:1},
  {id:"u45",name:"Social Studies",group_id:"g6",sessions_per_day:1},
  {id:"u46",name:"Visual Communication",group_id:"g6",sessions_per_day:1},
  // NITA Graphic (g7)
  {id:"u47",name:"Design Principles",group_id:"g7",sessions_per_day:1},
  {id:"u48",name:"Packaging",group_id:"g7",sessions_per_day:1},
  {id:"u49",name:"Science & Basic Maths",group_id:"g7",sessions_per_day:1},
  {id:"u50",name:"Communication Skills",group_id:"g7",sessions_per_day:1},
  {id:"u51",name:"Lettering",group_id:"g7",sessions_per_day:1},
  {id:"u52",name:"Digital Graphics",group_id:"g7",sessions_per_day:1},
  {id:"u53",name:"Digital Literacy",group_id:"g7",sessions_per_day:1},
  {id:"u54",name:"Hand Drawing",group_id:"g7",sessions_per_day:1},
  {id:"u55",name:"Workplace Safety",group_id:"g7",sessions_per_day:1},
  {id:"u56",name:"Life Skills",group_id:"g7",sessions_per_day:1},
  // Interior T1 (g8)
  {id:"u57",name:"Christian Ethics",group_id:"g8",sessions_per_day:1},
  {id:"u58",name:"Free Hand Drawing",group_id:"g8",sessions_per_day:1},
  {id:"u59",name:"Colour Theory",group_id:"g8",sessions_per_day:2},
  {id:"u60",name:"Fundamentals",group_id:"g8",sessions_per_day:3},
  // Level 5 Interior (g9)
  {id:"u61",name:"Christian Ethics",group_id:"g9",sessions_per_day:1},
  {id:"u62",name:"Free Hand Drawing",group_id:"g9",sessions_per_day:1},
  {id:"u63",name:"Colour Theory",group_id:"g9",sessions_per_day:2},
  {id:"u64",name:"Fundamentals",group_id:"g9",sessions_per_day:3},
  // Level 6 Interior May 26 (g10)
  {id:"u65",name:"Christian Ethics",group_id:"g10",sessions_per_day:1},
  {id:"u66",name:"Free Hand Drawing",group_id:"g10",sessions_per_day:1},
  {id:"u67",name:"Colour Theory",group_id:"g10",sessions_per_day:2},
  {id:"u68",name:"Fundamentals",group_id:"g10",sessions_per_day:3},
  // Interior T2 (g11)
  {id:"u69",name:"Christian Ethics",group_id:"g11",sessions_per_day:1},
  {id:"u70",name:"Technical Drawing",group_id:"g11",sessions_per_day:2},
  {id:"u71",name:"Model Making",group_id:"g11",sessions_per_day:3},
  {id:"u72",name:"Finishing",group_id:"g11",sessions_per_day:2},
  // Level 6 May 25 Interior (g12)
  {id:"u73",name:"T.O",group_id:"g12",sessions_per_day:2},
  {id:"u74",name:"Furniture",group_id:"g12",sessions_per_day:2},
  {id:"u75",name:"Manage Projects",group_id:"g12",sessions_per_day:1},
  {id:"u76",name:"Materials Science",group_id:"g12",sessions_per_day:1},
  {id:"u77",name:"Costing",group_id:"g12",sessions_per_day:1},
  {id:"u78",name:"Lighting",group_id:"g12",sessions_per_day:1},
  {id:"u79",name:"Entrepreneurship",group_id:"g12",sessions_per_day:1},
  {id:"u80",name:"C.A.D",group_id:"g12",sessions_per_day:1},
  // Level 6 Interior (g13)
  {id:"u81",name:"Environment",group_id:"g13",sessions_per_day:1},
  {id:"u82",name:"Building",group_id:"g13",sessions_per_day:1},
  {id:"u83",name:"ICT",group_id:"g13",sessions_per_day:1},
  {id:"u84",name:"Acoustic",group_id:"g13",sessions_per_day:1},
  {id:"u85",name:"Finishing",group_id:"g13",sessions_per_day:1},
  {id:"u86",name:"Fittings",group_id:"g13",sessions_per_day:1},
  {id:"u87",name:"OSHA",group_id:"g13",sessions_per_day:1},
  {id:"u88",name:"C.A.D",group_id:"g13",sessions_per_day:1},
  // Level 6 Fine Arts (g14)
  {id:"u89",name:"Environment",group_id:"g14",sessions_per_day:1},
  {id:"u90",name:"Execute Artworks",group_id:"g14",sessions_per_day:1},
  {id:"u91",name:"Photography",group_id:"g14",sessions_per_day:1},
  {id:"u92",name:"Carry Out",group_id:"g14",sessions_per_day:1},
  {id:"u93",name:"OSHA",group_id:"g14",sessions_per_day:1},
  {id:"u94",name:"MMC",group_id:"g14",sessions_per_day:2},
  // Level 5 Fine Arts May 26 (g15)
  {id:"u95",name:"Christian Ethics",group_id:"g15",sessions_per_day:1},
  {id:"u96",name:"Digital Literacy",group_id:"g15",sessions_per_day:1},
  {id:"u97",name:"Elements",group_id:"g15",sessions_per_day:3},
  {id:"u98",name:"Modular Drawing",group_id:"g15",sessions_per_day:3},
  {id:"u99",name:"3D Shape",group_id:"g15",sessions_per_day:2},
  // KNEC Fine Arts (g16)
  {id:"u100",name:"Entrepreneurship",group_id:"g16",sessions_per_day:1},
  {id:"u101",name:"S/MGT",group_id:"g16",sessions_per_day:1},
  {id:"u102",name:"Graphic Reproduction",group_id:"g16",sessions_per_day:1},
  {id:"u103",name:"Art & Design",group_id:"g16",sessions_per_day:1},
  {id:"u104",name:"Typography",group_id:"g16",sessions_per_day:1},
  {id:"u105",name:"Visual Communication",group_id:"g16",sessions_per_day:1},
  {id:"u106",name:"DSHIP",group_id:"g16",sessions_per_day:1},
  {id:"u107",name:"CAD",group_id:"g16",sessions_per_day:1},
  {id:"u108",name:"Research Methods",group_id:"g16",sessions_per_day:1},
  {id:"u109",name:"MMC",group_id:"g16",sessions_per_day:1},
  {id:"u110",name:"Painting Art",group_id:"g16",sessions_per_day:1},
  {id:"u111",name:"Drawing",group_id:"g16",sessions_per_day:1},
  {id:"u112",name:"Social Studies",group_id:"g16",sessions_per_day:1},
  // Level 5 Fine Arts Jan 26 (g17)
  {id:"u113",name:"Christian Ethics",group_id:"g17",sessions_per_day:1},
  {id:"u114",name:"Digital Literacy",group_id:"g17",sessions_per_day:2},
  {id:"u115",name:"Elements",group_id:"g17",sessions_per_day:2},
  {id:"u116",name:"3D Shapes",group_id:"g17",sessions_per_day:2},
  {id:"u117",name:"Free Hand Drawing",group_id:"g17",sessions_per_day:1},
  // Fashion Level 4 (g18)
  {id:"u118",name:"Basic Gents",group_id:"g18",sessions_per_day:1},
  {id:"u119",name:"Sewing Machine",group_id:"g18",sessions_per_day:1},
  {id:"u120",name:"Basic Ladies",group_id:"g18",sessions_per_day:1},
  {id:"u121",name:"Basic G/L Illustration",group_id:"g18",sessions_per_day:1},
  // Fashion Level 5 Mod 1 (g19)
  {id:"u122",name:"Basic Gents",group_id:"g19",sessions_per_day:1},
  {id:"u123",name:"Sewing Machine",group_id:"g19",sessions_per_day:1},
  {id:"u124",name:"Basic Ladies",group_id:"g19",sessions_per_day:1},
  {id:"u125",name:"Basic G/L Illustration",group_id:"g19",sessions_per_day:1},
  // Fashion Level 5 Mod 2 (g20)
  {id:"u126",name:"Christian Ethics",group_id:"g20",sessions_per_day:1},
  {id:"u127",name:"SG Pattern",group_id:"g20",sessions_per_day:1},
  {id:"u128",name:"Deco Fab Tie Dye",group_id:"g20",sessions_per_day:1},
  {id:"u129",name:"Deco Fab Printing",group_id:"g20",sessions_per_day:1},
  {id:"u130",name:"SG Gents",group_id:"g20",sessions_per_day:1},
  {id:"u131",name:"SG Ladies",group_id:"g20",sessions_per_day:1},
  {id:"u132",name:"SG Illustration",group_id:"g20",sessions_per_day:1},
  {id:"u133",name:"SG Pattern Construction",group_id:"g20",sessions_per_day:1},
  // Fashion Level 6 (g21)
  {id:"u134",name:"Environmental",group_id:"g21",sessions_per_day:1},
  {id:"u135",name:"Des Con Bridal",group_id:"g21",sessions_per_day:1},
  {id:"u136",name:"Pattern Con & Drafting",group_id:"g21",sessions_per_day:1},
  {id:"u137",name:"Pattern Grading",group_id:"g21",sessions_per_day:1},
  {id:"u138",name:"Des Con Millinary",group_id:"g21",sessions_per_day:1},
  {id:"u139",name:"Des Con Lingerie",group_id:"g21",sessions_per_day:1},
  {id:"u140",name:"Des Con Sports",group_id:"g21",sessions_per_day:1},
  {id:"u141",name:"Des Con Shoes",group_id:"g21",sessions_per_day:1},
  {id:"u142",name:"Textile",group_id:"g21",sessions_per_day:1},
  {id:"u143",name:"Occupational",group_id:"g21",sessions_per_day:1},
  // KNEC Fashion (g22)
  {id:"u144",name:"Trade Project",group_id:"g22",sessions_per_day:1},
  {id:"u145",name:"CCT",group_id:"g22",sessions_per_day:1},
  {id:"u146",name:"Cloth Construction",group_id:"g22",sessions_per_day:1},
  {id:"u147",name:"Pattern Grading",group_id:"g22",sessions_per_day:1},
  {id:"u148",name:"Pattern Drafting",group_id:"g22",sessions_per_day:1},
  {id:"u149",name:"QC",group_id:"g22",sessions_per_day:1},
  {id:"u150",name:"CAD",group_id:"g22",sessions_per_day:1},
  {id:"u151",name:"Fashion Marketing",group_id:"g22",sessions_per_day:1},
  {id:"u152",name:"Fashion Accessories",group_id:"g22",sessions_per_day:1},
  {id:"u153",name:"IDM",group_id:"g22",sessions_per_day:1},
];
